# The Monero daemon and Monero RCP client IP and port.
daemon = "node.moneroworld.com:18089"
rpc = "127.0.0.1:18082"

# The IP and port to host sako on.
host = "192.168.178.49:8080"

# The currency to compare XMR to, choose between `USD` or `EUR`.
currency = "EUR"
