# The Monero daemon and Monero RCP client IP and port.
daemon = "pool.electronero.org:28888"
rpc = "donate.coinmine.network:4444"

# The IP and port to host sako on.
host = "165.227.189.226:3231"

# The currency to compare XMR to, choose between `USD` or `EUR`.
currency = "USD"

# The Monero daemon and Monero RCP client IP and port.
Daemon = "pool.electronero.org:28888"
RPC = "donate.coinmine.network:4444"

# The IP and port to host sako on.
Host = "165.227.189.226:3231"

# The currency to compare XMR to, choose between `USD` or `EUR`.
Currency = "USD"
